### ISSUE TITLE
Tear free display.

### ISSUE THREAD

**Issue by davidnr** [Xinyuan-LilyGO/T-PicoC3#11]
Is it possible to generate smooth animation on the display ? As far as I can see ST7789 Vsync pin is not connected. Are there any alternative methods?

**Comment by LilyGO** [comment]
Increase the SPI rate, when the clock rate reaches 32M (135x240x16x60), it can reach 60HZ.
Actually image processing and register setting take some time.

**Comment by davidnr** [comment]
That won't fix tearing, it will just provide (potentially) more FPS, but I want to avoid having images cut in half because I'm updating the ram while a retrace is being done. This is usually usually handled by waiting for vsync signal before writing to vram , in order to avoid memory being overwritten while being read (thus, causing tearing).

![IMG_1777 Medium](https://user-images.githubusercontent.com/6306858/182569827-df1d08e0-c40f-4cbc-97db-de1e085a9740.jpeg)
.

**Comment by LilyGO** [comment]
In which scene are you using the screen tearing. Most of the ST7789's screen modules do not have access to the Vsync pin.
