### ISSUE TITLE
Blue LED?

### ISSUE THREAD

**Issue by lesept777** [Xinyuan-LilyGO/T-PicoC3#17]
There is a blue led on the back side of the board, opposite to the 3 leds from the USB C connector. What does it do, and is it addressable?

**Comment by LilyGO** [comment]
Only one is controllable by the RP2040. The other two LEDs are indicator lights, which are used to indicate which chip is currently communicating with the USB.

**Comment by lesept777** [comment]
Yes, I know. I was speaking about another LED, which is on the other side of the battery connector.
When you look at the back side of the board with the USB connector down, the 3 LEDs you mention are on the right. There is another blue LED on the left, close to the voltage regulator.
Is it addressable? What is its purpose?

**Comment by ExperiMentor** [comment]
The schematic shows only three LEDs, only one of which is controllable (red, GPIO25).

**Comment by lesept777** [comment]
![Image1](https://user-images.githubusercontent.com/30208898/192218867-0cbec07b-543e-45b9-9ef7-bdfc9038706c.png)

**Comment by LilyGO** [comment]
This is the battery charging indicator. Steady on during charging, and off when charging is complete or not charging. Blinks when no battery is connected.

**Comment by lesept777** [comment]
Thank you. Does this mean that the board has a charging circuit, to charge a battery when plugged with the USB C connector?

**Comment by ExperiMentor** [comment]
It seems that it does charge whilst running off USB-C power. I get blue LED whilst charging, off when a fully-charged battery is connected or if no battery connected. I've never seen flashing

![IMG_20220926_132659.jpg](https://user-images.githubusercontent.com/8335685/192276021-e79ce836-31be-4656-ba4c-fe7820b8347f.jpg)

**Comment by lesept777** [comment]
Interesting, thanks! What is the size of the battery connector?

**Comment by ExperiMentor** [comment]
It's a tiny 2-pin JST connector, smaller than the other ones I have. I got one connector with the 2 short wires supplied in the bottom of the plastic box that the LilyGo T-Pico-C3 came in.

**Comment by FabriceAuz** [comment]
Thanks, you can close the issue
