### ISSUE TITLE
Difficulties uploading to RP2040

### ISSUE THREAD

**Issue by jamesawebb** [Xinyuan-LilyGO/T-PicoC3#2]
Struggled forever to get the `RP2040` upload to work.  Turns out this wasn't going to happen with a `USB-C <-> USB-C` cable.  `USB-A <-> USB-C` did the trick.  Hope this benefits other n00bs.

**Comment by LilyGO** [comment]
Because the USB-C of this board is defined as two sets of functions, it is not possible to use USB-C TO UXB
