### ISSUE TITLE
driver for windows10

### ISSUE THREAD

**Issue by hajulied** [Xinyuan-LilyGO/T-PicoC3#27]
Hi,
I need support for a driver for windows 10. After plug-in of the board in esp32 mode, serial port 4(USB) appears. But it seems, that it is not fully functioning:
esptool.py v4.2.1
Serial port COM4

A fatal error occurred: Could not open COM4, the port doesn't exist
Fehlgeschlagenes Hochladen: Hochladefehler: exit status 2

**Comment by mmMicky** [comment]
To program ESP32-c3, you need to short IO9 and GND before powering on.
