### ISSUE TITLE
Help with TFT_eSPI library, not found in this GITHUB

### ISSUE THREAD

**Issue by Alanprime** [Xinyuan-LilyGO/T-PicoC3#8]
Hi, can you please upload the custom TFT_eSPI library here? original one requires modifications in order to get factory firmware to work and I can't seem to configure it correctly.

**Comment by mperino** [comment]
HI Alan,

Have you tried to follow the directions in my video:
https://youtu.be/FJF95bNKVFQ

**Comment by Alanprime** [comment]
Hi mperino, 
Thank you very much for your answer, I totally forgot to mention that I'm trying to program it on Arduino (I'm more used to Arduino C/C++ than Python). 
However, I'll try to follow your instructions and learn a phew things and then try to move that to Arduino. :) 

Thanks!

**Comment by LilyGO** [comment]
Looks like the problem has been resolved
